#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

@i = 0
# print "%F{1}/"

ARGV[0].split("/").each { |d|
   if d.length < 1 then
      @i -= 1
      d = "/"
   end

   print "%F{#{@i}} » " unless @i < 1
   print "%F{240}#{d}"
   @i += 1
}

if ARGV[0] == '/' then
   print "%F{240}#{ARGV[0]}"
end
