zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename $HOME'/.zshrc'

autoload -U compinit && compinit
autoload -U colors && colors
autoload -U vcs_info && vcs_info

zmodload zsh/complist
zmodload zsh/terminfo

# Environment Vars {{{
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}

for r in $HOME/.local/environment/*; do
   [[ $DEBUG > 0 ]] && echo "zsh: sourcing $r"
   source $r
done # }}}

# Plugin/Settings configs
FPATH=$FPATH:$XDG_CONFIG_HOME/zsh/prompts
PLUGIN_DIR=$XDG_CONFIG_HOME/zsh/plugins
ZSH_SETTINGS_DIR=$XDG_CONFIG_HOME/zsh/settings
ZSHRC=$HOME/.zshrc

# Shell options
setopt nobeep
setopt correct
setopt prompt_subst

# Load settings {{{
for r in $ZSH_SETTINGS_DIR/*.zsh; do
   [[ $DEBUG > 0 ]] && echo "zsh: sourcing $r"
   source $r
done # }}}
# set shell colors {{{
if [ -f $XDG_CONFIG_HOME/zsh/colors ]; then
   . $XDG_CONFIG_HOME/zsh/colors
fi # }}}

# set initial title using TTY, only if interactive
if [[ -o interactive ]]; then
   which settitle &>/dev/null && settitle
   which term_info &>/dev/null && term_info
fi

# vim: ft=zsh foldmethod=marker
