zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename $HOME'/.zshrc'

autoload -U compinit && compinit
autoload -U colors && colors
autoload -U vcs_info && vcs_info

zmodload zsh/complist
zmodload zsh/terminfo

# Environment Vars {{{
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache

for r in $HOME/.local/environment/*; do
   if [[ $DEBUG > 0 ]]; then
      echo "zsh: sourcing $r"
   fi
   source $r
done # }}}
# Lines configured by zsh-newuser-install
HISTFILE=$XDG_CACHE_HOME/histfile
HISTSIZE=10000
SAVEHIST=10000
# End of lines configured by zsh-newuser-install

FPATH=$FPATH:$XDG_CONFIG_HOME/zsh/prompts
PLUGIN_DIR=$XDG_CONFIG_HOME/zsh/plugins
ZSH_SETTINGS_DIR=$XDG_CONFIG_HOME/zsh/settings
ZSHRC=$HOME/.zshrc

# Shell options
setopt nobeep
setopt correct
setopt prompt_subst

# Load settings {{{
for r in $ZSH_SETTINGS_DIR/*.zsh; do
   if [[ $DEBUG > 0 ]]; then
      echo "zsh: sourcing $r"
   fi
   source $r
done # }}}
# set shell colors {{{
if [ -f $XDG_CONFIG_HOME/zsh/colors ]; then
   . $XDG_CONFIG_HOME/zsh/colors
fi # }}}

# set initial title using TTY
settitle

# vim: ft=zsh foldmethod=marker
